apiVersion: v1
data:
  03-ceph-nova.conf: |-
    [libvirt]
    images_type=rbd
    images_rbd_pool=vms
    images_rbd_ceph_conf=/etc/ceph/az0.conf
    images_rbd_glance_store_name=default_backend
    images_rbd_glance_copy_poll_interval=15
    images_rbd_glance_copy_timeout=600
    rbd_user=openstack
    rbd_secret_uuid=<FSID>
kind: ConfigMap
metadata:
  name: ceph-nova
  namespace: openstack
---
apiVersion: v1
data:
  ceph.client.openstack.keyring: <redacted>
  ceph.conf: <redacted>
kind: Secret
metadata:
  name: ceph-conf-files
  namespace: openstack
type: Opaque
---
apiVersion: v1
data:
  authorized_keys: <redacted>
  ssh-privatekey: <redacted>
  ssh-publickey: <redacted>
kind: Secret
metadata:
  name: dataplane-ansible-ssh-private-key-secret
  namespace: openstack
type: Opaque
---
apiVersion: v1
data:
  ssh-privatekey: <redacted>
  ssh-publickey: <redacted>
kind: Secret
metadata:
  name: nova-migration-ssh-key
  namespace: openstack
type: kubernetes.io/ssh-auth
---
apiVersion: v1
data:
  AdminPassword: <redacted>
  CeilometerPassword: <redacted>
  CinderDatabasePassword: <redacted>
  CinderPassword: <redacted>
  DatabasePassword: <redacted>
  DbRootPassword: <redacted>
  DesignateDatabasePassword: <redacted>
  DesignatePassword: <redacted>
  GlanceDatabasePassword: <redacted>
  GlancePassword: <redacted>
  HeatAuthEncryptionKey: <redacted>
  HeatDatabasePassword: <redacted>
  HeatPassword: <redacted>
  IronicDatabasePassword: <redacted>
  IronicInspectorDatabasePassword: <redacted>
  IronicInspectorPassword: <redacted>
  IronicPassword: <redacted>
  KeystoneDatabasePassword: <redacted>
  ManilaDatabasePassword: <redacted>
  ManilaPassword: <redacted>
  MetadataSecret: MTIzNDU2Nzg0Mg==
  NeutronDatabasePassword: <redacted>
  NeutronPassword: <redacted>
  NovaAPIDatabasePassword: <redacted>
  NovaCell0DatabasePassword: <redacted>
  NovaCell1DatabasePassword: <redacted>
  NovaPassword: <redacted>
  OctaviaDatabasePassword: <redacted>
  OctaviaPassword: <redacted>
  PlacementDatabasePassword: <redacted>
  PlacementPassword: <redacted>
  SwiftPassword: <redacted>
kind: Secret
metadata:
  name: osp-secret
  namespace: openstack
type: Opaque
---
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: controlplane
  namespace: openstack
spec:
  ceilometer:
    template:
      passwordSelector:
        service: CeilometerPassword
      secret: osp-secret
      serviceUser: ceilometer
  cinder:
    apiOverride:
      route: {}
    template:
      cinderAPI:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
      cinderBackup:
        customServiceConfig: |
          [DEFAULT]
          backup_driver = cinder.backup.drivers.ceph.CephBackupDriver
          backup_ceph_pool = backups
          backup_ceph_user = openstack
        networkAttachments:
        - storage
        replicas: 0
      cinderScheduler:
        replicas: 1
      cinderVolumes:
        ceph:
          customServiceConfig: |-
            [DEFAULT]
            enabled_backends=ceph
            [ceph]
            volume_backend_name=ceph
            volume_driver=cinder.volume.drivers.rbd.RBDDriver
            rbd_flatten_volume_from_snapshot=False
            rbd_pool=volumes
            rbd_ceph_conf=/etc/ceph/az0.conf
            rbd_user=openstack
            rbd_secret_uuid=<FSID>
      databaseInstance: openstack
      secret: osp-secret
  dns:
    template:
      options:
      - key: server
        values:
        - 192.168.122.1
      override:
        service:
          metadata:
            annotations:
              metallb.universe.tf/address-pool: ctlplane
              metallb.universe.tf/allow-shared-ip: ctlplane
              metallb.universe.tf/loadBalancerIPs: 192.168.122.80
          spec:
            type: LoadBalancer
      replicas: 1
  extraMounts:
  - extraVol:
    - extraVolType: Ceph
      mounts:
      - mountPath: /etc/ceph
        name: ceph
        readOnly: true
      propagation:
      - CinderVolume
      - CinderBackup
      - GlanceAPI
      - ManilaShare
      volumes:
      - name: ceph
        projected:
          sources:
          - secret:
              name: ceph-conf-files
    name: v1
    region: r1
  galera:
    enabled: true
    templates:
      openstack:
        replicas: 3
        secret: osp-secret
        storageRequest: 500M
      openstack-cell1:
        replicas: 3
        secret: osp-secret
        storageRequest: 500M
  glance:
    apiOverrides:
      default:
        route: {}
    template:
      customServiceConfig: |
        [DEFAULT]
        enabled_backends = default_backend:rbd
        [glance_store]
        default_backend = default_backend
        [default_backend]
        rbd_store_ceph_conf = /etc/ceph/ceph.conf
        store_description = "RBD backend"
        rbd_store_pool = images
        rbd_store_user = openstack
      databaseInstance: openstack
      glanceAPIs:
        default:
          networkAttachments:
          - storage
          override:
            service:
              internal:
                metadata:
                  annotations:
                    metallb.universe.tf/address-pool: internalapi
                    metallb.universe.tf/allow-shared-ip: internalapi
                    metallb.universe.tf/loadBalancerIPs: 172.17.0.80
                spec:
                  type: LoadBalancer
          replicas: 3
      storageClass: local-storage
      storageRequest: 10G
  heat:
    apiOverride:
      route: {}
    cnfAPIOverride:
      route: {}
    enabled: false
    template:
      databaseInstance: openstack
      heatAPI:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
      heatEngine:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
      secret: osp-secret
  horizon:
    apiOverride:
      route: {}
    enabled: true
    template:
      replicas: 1
      secret: osp-secret
  ironic:
    enabled: false
    template:
      databaseInstance: openstack
      ironicAPI:
        replicas: 1
      ironicConductors:
      - replicas: 1
        storageRequest: 10G
      ironicInspector:
        replicas: 1
      ironicNeutronAgent:
        replicas: 1
      secret: osp-secret
  keystone:
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      secret: osp-secret
  manila:
    apiOverride:
      route: {}
    enabled: true
    template:
      manilaAPI:
        networkAttachments:
        - internalapi
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
      manilaScheduler:
        replicas: 1
      manilaShares:
        share1:
          customServiceConfig: |
            [DEFAULT]
            enabled_share_backends = cephfs
            enabled_share_protocols = cephfs
            [cephfs]
            driver_handles_share_servers = False
            share_backend_name = cephfs
            share_driver = manila.share.drivers.cephfs.driver.CephFSDriver
            cephfs_conf_path = /etc/ceph/ceph.conf
            cephfs_cluster_name = ceph
            cephfs_auth_id=openstack
            cephfs_volume_mode = 0755
            cephfs_protocol_helper_type = CEPHFS
          networkAttachments:
          - storage
          replicas: 1
  mariadb:
    enabled: false
    templates:
      openstack:
        storageRequest: 500M
      openstack-cell1:
        storageRequest: 500M
  memcached:
    templates:
      memcached:
        replicas: 1
  neutron:
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      networkAttachments:
      - internalapi
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      secret: osp-secret
  nova:
    apiOverride:
      route: {}
    template:
      apiServiceTemplate:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
      metadataServiceTemplate:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      secret: osp-secret
  octavia:
    enabled: false
    template:
      databaseInstance: openstack
      octaviaAPI:
        replicas: 1
      secret: osp-secret
  ovn:
    template:
      ovnController:
        networkAttachment: tenant
        nicMappings:
          datacentre: ospbr
      ovnDBCluster:
        ovndbcluster-nb:
          dbType: NB
          networkAttachment: internalapi
          storageRequest: 10G
        ovndbcluster-sb:
          dbType: SB
          networkAttachment: internalapi
          storageRequest: 10G
      ovnNorthd:
        networkAttachment: internalapi
  placement:
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      secret: osp-secret
  rabbitmq:
    templates:
      rabbitmq:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.85
            spec:
              type: LoadBalancer
        replicas: 3
      rabbitmq-cell1:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.86
            spec:
              type: LoadBalancer
        replicas: 3
  redis:
    enabled: false
  secret: osp-secret
  storageClass: local-storage
  swift:
    enabled: false
    proxyOverride:
      route: {}
    template:
      swiftProxy:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
      swiftRing:
        ringReplicas: 1
      swiftStorage:
        replicas: 1
---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: edpm-deployment-post-ceph
  namespace: openstack
spec:
  nodeSets:
  - openstack-edpm
---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm
  namespace: openstack
spec:
  env:
  - name: ANSIBLE_FORCE_COLOR
    value: "True"
  networkAttachments:
  - ctlplane
  nodeTemplate:
    ansible:
      ansiblePort: 22
      ansibleUser: zuul
      ansibleVars:
        edpm_ceph_hci_pre_enabled_services:
        - ceph_mon
        - ceph_mgr
        - ceph_osd
        - ceph_rgw
        - ceph_nfs
        - ceph_rgw_frontend
        - ceph_nfs_frontend
        edpm_iscsid_image: '{{ registry_url }}/openstack-iscsid:{{ image_tag }}'
        edpm_logrotate_crond_image: '{{ registry_url }}/openstack-cron:{{ image_tag
          }}'
        edpm_network_config_hide_sensitive_logs: false
        edpm_network_config_os_net_config_mappings:
          edpm-compute:
            nic2: eth1
          edpm-compute-0:
            nic2: 6a:fe:54:3f:8a:02
          edpm-compute-1:
            nic2: 6b:fe:54:3f:8a:02
          edpm-compute-2:
            nic2: 6c:fe:54:3f:8a:02
        edpm_network_config_template: |
          ---
          {% set mtu_list = [ctlplane_mtu] %}
          {% for network in role_networks %}
          {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
          {%- endfor %}
          {% set min_viable_mtu = mtu_list | max %}
          network_config:
          - type: ovs_bridge
            name: {{ neutron_physical_bridge_name }}
            mtu: {{ min_viable_mtu }}
            use_dhcp: false
            dns_servers: {{ ctlplane_dns_nameservers }}
            domain: {{ dns_search_domains }}
            addresses:
            - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}
            routes: {{ ctlplane_host_routes }}
            members:
            - type: interface
              name: nic2
              mtu: {{ min_viable_mtu }}
              # force the MAC address of the bridge to this interface
              primary: true
          {% for network in role_networks %}
            - type: vlan
              mtu: {{ lookup('vars', networks_lower[network] ~ '_mtu') }}
              vlan_id: {{ lookup('vars', networks_lower[network] ~ '_vlan_id') }}
              addresses:
              - ip_netmask:
                  {{ lookup('vars', networks_lower[network] ~ '_ip') }}/{{ lookup('vars', networks_lower[network] ~ '_cidr') }}
              routes: {{ lookup('vars', networks_lower[network] ~ '_host_routes') }}
          {% endfor %}
        edpm_neutron_metadata_agent_image: '{{ registry_url }}/openstack-neutron-metadata-agent-ovn:{{
          image_tag }}'
        edpm_nodes_validation_validate_controllers_icmp: false
        edpm_nodes_validation_validate_gateway_icmp: false
        edpm_nova_compute_container_image: '{{ registry_url }}/openstack-nova-compute:{{
          image_tag }}'
        edpm_nova_libvirt_container_image: '{{ registry_url }}/openstack-nova-libvirt:{{
          image_tag }}'
        edpm_ovn_controller_agent_image: '{{ registry_url }}/openstack-ovn-controller:{{
          image_tag }}'
        edpm_selinux_mode: enforcing
        edpm_sshd_allowed_ranges:
        - 192.168.122.0/24
        - 192.168.111.0/24
        edpm_sshd_configure_firewall: true
        enable_debug: false
        gather_facts: false
        image_tag: current-podified
        neutron_physical_bridge_name: br-ex
        neutron_public_interface_name: eth0
        registry_url: quay.io/podified-antelope-centos9
        service_net_map:
          nova_api_network: internalapi
          nova_libvirt_network: internalapi
        storage_mgmt_cidr: "24"
        storage_mgmt_host_routes: []
        storage_mgmt_mtu: 9000
        storage_mgmt_vlan_id: 23
        storage_mtu: 9000
        timesync_ntp_servers:
        - hostname: pool.ntp.org
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    extraMounts:
    - extraVolType: Ceph
      mounts:
      - mountPath: /etc/ceph
        name: ceph
        readOnly: true
      volumes:
      - name: ceph
        secret:
          secretName: ceph-conf-files
    managementNetwork: ctlplane
    networks:
    - defaultRoute: true
      name: CtlPlane
      subnetName: subnet1
    - name: InternalApi
      subnetName: subnet1
    - name: Storage
      subnetName: subnet1
    - name: Tenant
      subnetName: subnet1
    - name: StorageMgmt
      subnetName: subnet1
  nodes:
    edpm-compute-0:
      ansible:
        host: 192.168.122.100
      hostName: compute-0
      networks:
      - defaultRoute: true
        fixedIP: 192.168.122.100
        name: ctlplane
        subnetName: subnet1
      - name: internalapi
        subnetName: subnet1
      - name: storage
        subnetName: subnet1
      - name: storagemgmt
        subnetName: subnet1
      - name: tenant
        subnetName: subnet1
    edpm-compute-1:
      ansible:
        host: 192.168.122.101
      hostName: compute-1
      networks:
      - defaultRoute: true
        fixedIP: 192.168.122.101
        name: ctlplane
        subnetName: subnet1
      - name: internalapi
        subnetName: subnet1
      - name: storage
        subnetName: subnet1
      - name: storagemgmt
        subnetName: subnet1
      - name: tenant
        subnetName: subnet1
    edpm-compute-2:
      ansible:
        host: 192.168.122.102
      hostName: compute-2
      networks:
      - defaultRoute: true
        fixedIP: 192.168.122.102
        name: ctlplane
        subnetName: subnet1
      - name: internalapi
        subnetName: subnet1
      - name: storage
        subnetName: subnet1
      - name: storagemgmt
        subnetName: subnet1
      - name: tenant
        subnetName: subnet1
  preProvisioned: true
  services:
  - ceph-client
  - ovn
  - neutron-metadata
  - libvirt
  - nova-custom-ceph
---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: nova-custom-ceph
  namespace: openstack
spec:
  configMaps:
  - ceph-nova
  label: dataplane-deployment-nova-custom-ceph
  playbook: osp.edpm.nova
  secrets:
  - nova-cell1-compute-config
  - nova-migration-ssh-key
